### ISSUE TITLE
x11-libs/bamf: possibly missing a dependency on gtk+:2

### ISSUE THREAD

**Issue by threeway** [zhtengw/deepin-overlay#10]
When doing a completely fresh install (no other desktop environments, or even X installed), bamf seems to fail to eautoreconf properly, and the autoconf.out file says

```
***** autoconf *****
***** PWD: /var/tmp/portage/x11-libs/bamf-0.2.118/work/bamf-0.2.118
***** autoconf --force

configure.in:140: error: possibly undefined macro: AM_PATH_GTK_2_0
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

This seems that it needs to have gtk+:2 installed order for the test to pass, be patched out to only support 3 (which seems to be upstream's route in the latest version (0.5.3)), or put https://gnunet.org/svn/gnunet-gtk/m4/gtk-2.0.m4 into the m4 directory.  

Based on upstream's working, and the fact that we dep on gtk+:3, I think the last one would be best, as it would keep gtk+:2 off the system if it's not needed and it's not a true dependency. Just for the check.

**Comment by zhtengw** [comment]
I have the version of bamf bump to 0.5.3. Please have a check.
If you have the old bamf-0.2.118 merged, please "emerge -C bamf" first.

**Comment by threeway** [comment]
Bumped version works.
