### ISSUE TITLE
Wrong download location for dde-extra/deepin-voice-note-5.7.8 

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#105]
Hello, the download loaction for dde-extra/deepin-voice-note-5.7.8 is incorrect. Below is the portage output:

>>> Emerging (1 of 1) dde-extra/deepin-voice-note-5.7.8::deepin
>>> Downloading 'http://distfiles.gentoo.org/distfiles/8a/deepin-voice-note-5.7.8.tar.gz'
--2020-07-26 09:54:52--  http://distfiles.gentoo.org/distfiles/8a/deepin-voice-note-5.7.8.tar.gz
Resolving distfiles.gentoo.org... 13.227.223.33, 13.227.223.47, 13.227.223.5, ...
Connecting to distfiles.gentoo.org|13.227.223.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-26 09:54:52 ERROR 404: Not Found.

>>> Downloading 'https://github.com/linuxdeepin/deepin-voice-note/archive/5.7.8.tar.gz'
--2020-07-26 09:54:53--  https://github.com/linuxdeepin/deepin-voice-note/archive/5.7.8.tar.gz
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/linuxdeepin/deepin-voice-note/tar.gz/5.7.8 [following]
--2020-07-26 09:54:53--  https://codeload.github.com/linuxdeepin/deepin-voice-note/tar.gz/5.7.8
Resolving codeload.github.com... 140.82.114.9
Connecting to codeload.github.com|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-26 09:54:53 ERROR 404: Not Found.

!!! Couldn't download 'deepin-voice-note-5.7.8.tar.gz'. Aborting.

>>> Failed to emerge dde-extra/deepin-voice-note-5.7.8, Log file:

>>>  '/var/tmp/portage/dde-extra/deepin-voice-note-5.7.8/temp/build.log'

**Comment by zhtengw** [comment]
Upstream has removed the tag 5.7.8. Now updated and fixed.
