### ISSUE TITLE
dde-extra/deepin-log-viewer-5.6.18 compilation error on openrc

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#106]
Hello, I run into some compilation error with deepin-log-viewer and suspect it has something to do with the fact that I'm using openrc, but am not sure. I‘ve attached the build log. 

[build.log](https://github.com/zhtengw/deepin-overlay/files/4977344/build.log)

**Comment by zhtengw** [comment]
c650f2b may fix this.
