### ISSUE TITLE
Go packages aren't fully compatible with Go 1.8

### ISSUE THREAD

**Issue by yukiisbored** [zhtengw/deepin-overlay#12]
It turns out the main problem with go packages in this overlay is most of the projects Makefile aren't updated to Go 1.8. Go 1.7.x works flawlessly when merging.

**Comment by zhtengw** [comment]
Thanks for your report. I am using dev-lang/go-1.8 in my machine, but I can not recreate this issue.
Did you just update gcc from 4.x to 5.3?
Please try remerge dev-lang/go by 'emerge -1 "=dev-lang/go-1.8" '

**Comment by threeway** [comment]
I can recreate the issue that @yukiisbored has.  I installed dev-lang/go after gcc, so there wasn't an update to gcc beforehand.  

I simply downgraded to go 1.7.x for the moment as there are more pressing issues that I'd rather look into.

**Comment by yukiisbored** [comment]
@threeway so it's more of a problem with GCC. Makes sense because I can't reproduce it.

**Comment by yukiisbored** [comment]
Okay, I think I know the problem. I emerged `gcc` with `gccgo` enabled and haven't rebuild `go` and it results in `go` (not `gccgo`) linking with `ld` fails.
