### ISSUE TITLE
Installing to wrong libdir

### ISSUE THREAD

**Issue by threeway** [zhtengw/deepin-overlay#13]
I've forked the repo, and will (eventually) send a pull request to fix it, but currently both dde-qt-dbus-factory and dtksettings install their so files to /usr/lib.

This works fine on a system where /usr/lib is a symlink to /usr/lib64 (in the case of 64bit), but in newer gentoo systems, /usr/lib is apparently the old /usr/libexec - so what ends up happening is that anything that depends on dde-qt-dbus-factory or dtksettings will fail to build because it can't find the so files to link against them.

I thought it would be a simple matter of passing LIBDIR="/usr/$(get_libdir)" to the eqmake5 in prepare, and while that does seem to pass the proper libdir, the packages seem to hardcode installing into /usr/lib.

**Comment by zhtengw** [comment]
Hi @threeway,
Thank you for your advice.
I try to using $(get_libdir) in every ebuilds. Please test with the latest commit to see if it fits your need. 
If you find out more ebuild should be modified, please let me know or you could open pull requests.

**Comment by threeway** [comment]
Seeming to be okay so far, however, will open a new issue for something discovered :) in the process

**Comment by threeway** [comment]
deepin-mutter needs to pass --libdir=/usr/$(get_libdir) to the autogen, otherwise it too installs to /usr/lib

**Comment by zhtengw** [comment]
Thank you! The deepin-mutter-3.20.13.ebuild modified.

**Comment by threeway** [comment]
I've done a full rebuild and looks like everything is installing to the correct place now :)
