### ISSUE TITLE
deepin-music-3.0.5-r1 missing dependency on libcue and should also depend on >=taglib-1.10

### ISSUE THREAD

**Issue by threeway** [zhtengw/deepin-overlay#15]
Project ERROR: libcue development package not found

**Comment by threeway** [comment]
In file included from /usr/include/taglib/tag.h:30:0,
                 from metadetector.cpp:20:
metadetector.cpp: In static member function ‘static void MetaDetector::updateMediaFileTagCodec(MediaMeta*, const QByteArray&, bool)’:
metadetector.cpp:78:22: error: ‘class QString’ has no member named ‘utf8’; did you mean ‘utf16’?
     auto mediaPath = QStringToTString(meta->localPath);
                      ^

**Comment by zhtengw** [comment]
Thank you! Fixed.
