### ISSUE TITLE
wrong lrelease 

### ISSUE THREAD

**Issue by steev** [zhtengw/deepin-overlay#19]
Hi, a while back a bug was opened about lrelease not being correct.  I'm running into this again, although I'm not strictly sure what the proper fix is.

Packages in portage (e.g. app-editors/ghostwriter) do something along the lines of

``` src_prepare() {
    default

    local mylrelease="$(qt5_get_bindir)"/lrelease

    sed -i -e "/^VERSION =/s/\$.*/${PV}/" ghostwriter.pro || die "failed to override version"

    prepare_locale() {
        "${mylrelease}" "translations/${PN}_${1}.ts" || die "failed to prepare ${1} locale"
    }

    l10n_find_plocales_changes translations ${PN}_ .ts
    l10n_for_each_locale_do prepare_locale
} `


However, it seems here when the failures are occurring, it's because there is a script in the source

` #!/bin/bash
# this file is used to auto-generate .qm file from .ts file.
# author: shibowen at linuxdeepin.com

ts_list=(ls translations/*.ts)

for ts in "${ts_list[@]}"
do
    printf "\nprocess ${ts}\n"
    lrelease "${ts}"
done`

It seems like we would need to patch every package that has a lrelease script to properly run lrelease -qt5, or add $(qt5_get_bindir) to the path (first) so that it calls that lrelease - modifying the script locally it runs correctly when passing the /usr/lib64/qt5/bin/lrelease however that's only correct for amd64 machines, so it would break 64bit builds.

Maybe we should just sed in the path to the translate_generation.sh file(s) in the packages?

**Comment by steev** [comment]
For dtkwidget, i've done

src_prepare() {
	local mylrelease=$(qt5_get_bindir)/lrelease
	sed -i -e "s:lrelease:${mylrelease}:" tool/translate_generation.sh || die
	eqmake5 PREFIX=/usr LIB_INSTALL_DIR=/usr/$(get_libdir) LRELEASE_EXECUTABLE="$(qt5_get_bindir)/lrelease"
	default_src_prepare
}

Which does seem to work well enough, and since they don't seem to change the filename much, if at all, I think that's what I'll do, unless you have a better suggestion.

**Comment by zhtengw** [comment]
I find out that while adding QT_SELECT=qt5 before qmake, the lrelease script can run without error. Could you please test it in your system?

src_prepare() {
QT_SELECT=qt5 eqmake5 PREFIX=/usr LIB_INSTALL_DIR=/usr/$(get_libdir)
default_src_prepare
}

Best regards
Aten

**Comment by steev** [comment]
I haven't tested it, but I think that might work if it sets some sort of QT environment variables. 

I went the sed route because I wasn't sure how to get the environment to the bash and python scripts that were being run.

I will try later today when I have a chance, and if that works, I'll redo the pull request.

**Comment by steev** [comment]
Just a quick run here, it seems to work for dde-dock, so I'll test the others as well.  

I'm currently rebuilding everything installed on that system so it's gonna be a while before it's done due to it having been a really old system (wasn't updated in ~3 years) so there were some weirdness issues wrt OpenGL/GLES (it's an arm system) - once it's done, I'll submit a new pull request; gonna close this out though.
