### ISSUE TITLE
dev-cpp/treefrog-framework

### ISSUE THREAD

**Issue by inukyou** [zhtengw/deepin-overlay#29]
![deepinscreenshot_select-area_20171204082647](https://user-images.githubusercontent.com/27729836/33543494-2a5f33a2-d8cf-11e7-87a0-c67726a2fce1.png)
![deepinscreenshot_select-area_20171204082721](https://user-images.githubusercontent.com/27729836/33543495-2a8d3978-d8cf-11e7-8ce8-e8e3c28fa585.png)

**Comment by zhtengw** [comment]
Thank you. Version bump to 1.19.0 and fixed.

Best Regards,
Aten Zhang
