### ISSUE TITLE
[USE Flag] widgets USE flag shall be enabled for dev-qt/qtmultimedia

### ISSUE THREAD

**Issue by IAmMattD** [zhtengw/deepin-overlay#3]
dde-base/deepin-tool-kit requires dev-qt/qtmultimedia:5. However, the USE flag "widgets" for dev-qt/qtmultimedia is not enabled by default, which will cause build error for deepin-tool-kit.

Thus, please require "widgets" enabled for dev-qt/qtmultimedia in dependency of deepin-tool-kit.

**Comment by zhtengw** [comment]
Ok，thank you very much!
