### ISSUE TITLE
polkit-qt USE flag

### ISSUE THREAD

**Issue by ziyouwa** [zhtengw/deepin-overlay#30]
dde-file-manager一直依赖这个qt5标记，但是官方的polkit-qt 包里面没有，麻烦处理一下，谢谢！

emerge: there are no ebuilds built with USE flags to satisfy "sys-auth/polkit-qt[qt5]".
!!! One of the following packages is required to complete your request:
- sys-auth/polkit-qt-0.112.0_p20160416-r1::gentoo (Missing IUSE: qt5)
(dependency required by "dde-base/dde-file-manager-4.2.5-r2::gentoo-zh" [ebuild])
(dependency required by "dde-base/dde-meta-15.4.1::gentoo-zh" [ebuild])
(dependency required by "dde-meta" [argument])

**Comment by zhtengw** [comment]
您好，sys-auth/polkit-qt::gentoo有两个版本，稳定版的0.112.0-r1包含USE标记qt5，测试版的(~)0.112.0_p20160416-r1不包含qt5标记，为能正确处理对这两个版本的sys-auth/polkit-qt的依赖，我已将 dde-base/dde-file-manager和 dde-base/dde-polkit-agent的依赖关系调整为( https://github.com/zhtengw/deepin-overlay/commit/04b0f4e9060d8f5d42f9961195454170eb1fd949 )：
```
...
sys-auth/polkit-qt[qt5(+)]
...
```

请用layman -s deepin更新。

**Comment by ziyouwa** [comment]
非常感谢！
