### ISSUE TITLE
dde-extra/deepin-terminal-2.9.2 missing a sed

### ISSUE THREAD

**Issue by steev** [zhtengw/deepin-overlay#31]
Because deepin-terminal includes zssh, we need to fix it's configure in a way similar to how zssh itself in the tree is.

I added
`sed -i -e 's/-ltermcap/-ltinfo/g' 3rdparty/zssh-1.5c/configure || die`
before the
`cmake-utils_src_prepare`
line in src_prepare.

The comment in zssh's build is:
Fix linking with sys-libs/ncurses[tinfo], gentoo bug #527036

**Comment by zhtengw** [comment]
Thank you. Fixed with https://github.com/zhtengw/deepin-overlay/commit/914cde259e263367393c9d1a2d63549cbb92f59d
