### ISSUE TITLE
dde-base/dde-api should depend on net-wireless/rfkill OR >=sys-apps/util-linux-2.31

### ISSUE THREAD

**Issue by TrackScream** [zhtengw/deepin-overlay#32]
Latest util-linux already includes rfkill and blocks the installation of the corresponding package.

>  * Error: The above package list contains packages which cannot be
>  * installed at the same time on the same system.
> 
> (net-wireless/rfkill-0.5-r3:0/0::gentoo, ebuild scheduled for merge) pulled in by
>     net-wireless/rfkill required by (dde-base/dde-api-3.1.18:0/0::deepin, ebuild scheduled for merge)
> 
>   (sys-apps/util-linux-2.31:0/0::gentoo, installed) pulled in by
>     >=sys-apps/util-linux-2.20 required by (sys-block/gparted-0.29.0:0/0::gentoo, installed)
>     sys-apps/util-linux required by (app-text/build-docbook-catalog-1.21:0/0::gentoo, installed)
>     >=sys-apps/util-linux-2.16 required by (dev-libs/apr-1.6.3:1/1::gentoo, installed)
>     sys-apps/util-linux required by (sys-block/partitionmanager-3.2.1:5/5::gentoo, installed)
>     >=sys-apps/util-linux-2.27 required by (sys-libs/libblockdev-2.15-r1:0/0::gentoo, installed)
>     sys-apps/util-linux required by (app-emulation/vmware-workstation-14.0.0.6661328-r10:0/0::local, installed)
>     . . .
>     and so on

**Comment by zhtengw** [comment]
Thank you, fixed with https://github.com/zhtengw/deepin-overlay/commit/1402bb992c001ddd492e501ac0721ba0b0d044f9.
