### ISSUE TITLE
rfkill is obsolete

### ISSUE THREAD

**Issue by ziyouwa** [zhtengw/deepin-overlay#33]
官方portage树里面的rfkill已经过时了，它的依赖和util-linux包冲突。后者里面已经包含了rfkill，而且util-linux是每个系统的必装包，所以麻烦dde-api的依赖里面去掉net-wireless/rfkill。谢谢！

**Comment by ziyouwa** [comment]
不好意思，才看到已经更新了，是gentoo-zh里面没更新。

**Comment by zhtengw** [comment]
@ziyouwa gentoo-zh那我提交了pull request，但还没被合并。
