### ISSUE TITLE
Can't compile dde-base/dde-daemon

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#34]
Hello, I got the following error while compiling dde-base/dde-daemon (in the log below).

/var/log/portage/dde-base:dde-daemon-3.2.8:20180225-122538.log

Do you know what to do about it?

**Comment by zhtengw** [comment]
Sorry, your log was located in your own system :) . I can not view it here. Could you please upload it?

**Comment by SleepyMario** [comment]
Sorry, i had to go for a while. It's working now. I've no idea what was wrong, but hey, it's fixed!
