### ISSUE TITLE
media-video/deepin-movie-reborn-3.2.0.3 fails to compile on new system

### ISSUE THREAD

**Issue by kde99** [zhtengw/deepin-overlay#35]
Hello everyone!

Currently I'm in progress of installing gentoo on my pc. I was merging dde-meta when this package failed with this error below:

```
/var/tmp/portage/media-video/deepin-movie-reborn-3.2.0.3/work/deepin-movie-reborn-3.2.0.3/src/backends/mpv/mpv_glwidget.cpp:130:29: error: expected initializer before ‘glMPGetNativeDisplay’
     static void* GLAPIENTRY glMPGetNativeDisplay(const char* name) {
                             ^~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/media-video/deepin-movie-reborn-3.2.0.3/work/deepin-movie-reborn-3.2.0.3/src/backends/mpv/mpv_glwidget.cpp:689:1: error: expected ‘}’ at end of input
 }
 ^
```

I was wondering if anyone got to fix it. Thanks for the help.

Env: https://paste.pound-python.org/show/FSLoaxUheTiFDb6dN5bN/
emerge --info: https://paste.pound-python.org/show/ld123WfeWRgj1u0cpsOm/
Build log: https://paste.pound-python.org/show/wPQpWOXmTryEb2tRvLvY/

**Comment by zhtengw** [comment]
Package updated to deepin-movie-reborn-3.2.7. Please sync this overlay and upgrade to test.

**Comment by zhtengw** [comment]
No response. Fixed in my system.
