### ISSUE TITLE
Missing dependency for media-video/deepin-movie and dde-extra/deepin-social-sharing

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#37]
Hello, dde-extra/deepin-gettext-tools seems to be missing in the overlay.

**Comment by SleepyMario** [comment]
I figured that it's called dde-base/deepin-gettext-tools, so it's probably a typo in the ebuild?

**Comment by zhtengw** [comment]
Yes, I ignored them. In late 2017, deepin-gettext-tools became an essential dependency for many DDE packages. So I moved it from dde-extra/ to dde-base/, see profiles/updates/4Q-2017. But I forgot to change the dependency in media-video/deepin-movie and dde-extra/deepin-social-sharing. Thank you very much.
By the way, deepin-movie will not be updated anymore. I suggest to use deepin-movie-reborn instead.

**Comment by zhtengw** [comment]
Fixed.
