### ISSUE TITLE
dev-qt/qt5dxcb-plugin Error: Not supported Qt version 5.9.4

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#38]
Hello again, this package does compile fine when taken straight from upstream, but when using the ebuild it gives the error below (both for this one and the newest version upstream). 

https://paste.pound-python.org/show/3YgnHdSaccMXLGIjYCMx/

Thanks!

**Comment by zhtengw** [comment]
dev-qt/qt5dxcb-plugin is updated and this issue is solved.

**Comment by zhtengw** [comment]
Fixed.
