### ISSUE TITLE
emerge: there are no ebuilds to satisfy "x11-proto/xcb-proto".

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#39]
x11-proto/xcb-proto is not in the main repo. 
It should probably be renamed to x11-base/xcb-proto? (That's my very uneducated guess.)

Thanks for your great work on making deepin work on Gentoo!

This is the exact error that popped up while attempting an update:

------
emerge: there are no ebuilds to satisfy "x11-proto/xcb-proto".
(dependency required by "media-video/deepin-movie-reborn-3.2.0.3::deepin" [installed])
(dependency required by "dde-extra/dde-meta-multimedia-0.2-r1::deepin" [installed])
(dependency required by "dde-base/dde-meta-15.5::deepin[multimedia]" [installed])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])

**Comment by zhtengw** [comment]
I just updated the portage tree, and found out that x11-proto/xcb-proto was moved to x11-base/xcb-proto. I will fix this in next commit.
