### ISSUE TITLE
dde-dock compile can't find dde-network-utils

### ISSUE THREAD

**Issue by ziyouwa** [zhtengw/deepin-overlay#41]
-- Checking for module 'dde-network-utils'
--   No package 'dde-network-utils' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:436 (message):
  A required package was not found
.......
-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/dde-base/dde-dock-4.6.7/work/dde-dock-4.6.7_build/CMakeFiles/CMakeOutput.log".

===============================
yj@work ~ $ eix dde-network-utils
[I] dde-base/dde-network-utils [1]
     Available versions:  (~)0.0.3
     Installed versions:  0.0.3(10时01分09秒 2018年07月30日)
     Homepage:            https://github.com/linuxdeepin/dde-network-utils
     Description:         DDE Network Utils

[1] "deepin" /var/lib/layman/deepin

**Comment by zhtengw** [comment]
The dde-base/dde-network-utils has been writen as a dependency in dde-base/dde-dock-4.6.7.ebuild. Use "emerge" command to resolve the dependence list.

**Comment by ziyouwa** [comment]
It's OK now. Perhaps the problem is that I used experiment profile.
