### ISSUE TITLE
dde-file-manage dependon problem

### ISSUE THREAD

**Issue by ziyouwa** [zhtengw/deepin-overlay#42]
dde-file-manager depends on deepin-movie-player, and deepin-movie-player depends on xpyb.  There is no  xpyb in gentoo's portage now.
dde-video-previews-plugin  in dde-file-manage need deepin-movie-player, maybe remove the depends?

**Comment by zhtengw** [comment]
Actually, the dde-video-previews-plugin in dde-file-manage depends on media-video/deepin-movie-reborn. It's my fault to forget writing the dependency down. I summited an update.

**Comment by ziyouwa** [comment]
You are right. It's OK now. Thanks!
