### ISSUE TITLE
gsettings-qt need to be updated

### ISSUE THREAD

**Issue by lsblk** [zhtengw/deepin-overlay#46]
when I build deepin-terminal .the dependency gsettings-qt can't find source file.It seems that deepin update the package.

**Comment by zhtengw** [comment]
The source package is still there http://packages.linuxdeepin.com/ubuntu/pool/main/g/gsettings-qt/gsettings-qt_0.1%2b16.04.20160329.orig.tar.gz, and nothing update.

**Comment by schmidicom** [comment]
similar problem here:
"x11-libs/gsettings-qt-0.1_p20170824" fails on donwload.
```
>>> Unpacking source...
 * bzr branch start -->
 *    repository: lp:gsettings-qt => /usr/portage/distfiles/bzr-src/gsettings-qt
You have not informed bzr of your Launchpad ID, and you must do this to
write to Launchpad or access private data.  See "bzr help launchpad-login".
```
"x11-libs/gsettings-qt-0.2" works.
