### ISSUE TITLE
Missing deps

### ISSUE THREAD

**Issue by temnyuk** [zhtengw/deepin-overlay#49]
To emerge media-libs/cogl-1.22.5::deepin need sys-devel/automake:1.15

**Comment by zhtengw** [comment]
The sys-devel/automake-1.15 is provided by offical portage tree.

**Comment by temnyuk** [comment]
Of course.
But you need to specify it in dependencies.
It is not installed on the "clean" system.

**Comment by zhtengw** [comment]
I'm sorry.
Thank you very much.
Fixed now by https://github.com/zhtengw/deepin-overlay/commit/229790d3b88f5d221a04c636a731ceb998a18959.
