### ISSUE TITLE
Can't fetch media-gfx/byzanz

### ISSUE THREAD

**Issue by SleepyMario** [zhtengw/deepin-overlay#50]
Hello, it's not possible to fetch the sources of media-gfx/byzanz (using portage) and I'm not entirely sure where to get them either. They moved to gitlab, is this correct?

**Comment by zhtengw** [comment]
Thank you. Source URL updated https://github.com/zhtengw/deepin-overlay/commit/c9833be1ab91306c88a825fcc3da982666d6481c.
