### ISSUE TITLE
[Funtoo] only gcc-8 (masked) has [go] flag in portage

### ISSUE THREAD

**Issue by funkycode** [zhtengw/deepin-overlay#53]
Trying it on funtoo, and it seems that gcc with go flag is not available on 7.4 and 8.2 is hard masked.
Why not using go compiler instead?

**Comment by zhtengw** [comment]
On some earlier version of DDE, some packages depend on gcc[go]. Now I will do a test.

**Comment by zhtengw** [comment]
Fixed with https://github.com/zhtengw/deepin-overlay/commit/998e8e3f4a5a4ad9b0b251575fa9c482eb9c3317
