### ISSUE TITLE
dde-base/dde-daemon failed

### ISSUE THREAD

**Issue by xiecanlin** [zhtengw/deepin-overlay#54]
* Package:    dde-base/dde-daemon-3.22.0
 * Repository: deepin
 * Maintainer: atenzd@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking dde-daemon-3.22.0.tar.gz to /var/tmp/portage/dde-base/dde-daemon-3.22.0/work
>>> Source unpacked in /var/tmp/portage/dde-base/dde-daemon-3.22.0/work
>>> Preparing source in /var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0 ...
 * Applying 3.8.0-disable-tap-gesture.patch ...
 [ ok ]
github.com/msteinert/pam (download)
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0 ...
make -j4
env GOPATH="/var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0/gopath:/var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0:/usr/share/gocode" go build -o out/bin/default-terminal  pkg.deepin.io/dde/daemon/bin/default-terminal
gcc bin/default-file-manager/main.c -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -lgio-2.0 -lgobject-2.0 -lglib-2.0  -o out/bin/default-file-manager
can't load package: package pkg.deepin.io/dde/daemon/bin/default-terminal: cannot find package "pkg.deepin.io/dde/daemon/bin/default-terminal" in any of:
        /usr/lib/go/src/pkg.deepin.io/dde/daemon/bin/default-terminal (from $GOROOT)
        /var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0/gopath/src/pkg.deepin.io/dde/daemon/bin/default-terminal (from $GOPATH)
        /var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0/src/pkg.deepin.io/dde/daemon/bin/default-terminal
        /usr/share/gocode/src/pkg.deepin.io/dde/daemon/bin/default-terminal
make: *** [Makefile:33: out/bin/default-terminal] Error 1
make: *** Waiting for unfinished jobs....
 * ERROR: dde-base/dde-daemon-3.22.0::deepin failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=dde-base/dde-daemon-3.22.0::deepin'`,
 * the complete build log and the output of `emerge -pqv '=dde-base/dde-daemon-3.22.0::deepin'`.
 * The complete build log is located at '/var/tmp/portage/dde-base/dde-daemon-3.22.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dde-base/dde-daemon-3.22.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0'
 * S: '/var/tmp/portage/dde-base/dde-daemon-3.22.0/work/dde-daemon-3.22.0'

**Comment by xiecanlin** [comment]
emerge --info '=dde-base/dde-daemon-3.22.0::deepin'
Portage 2.3.51 (python 3.6.5-final-0, default/linux/amd64/17.0/systemd, gcc-8.2.0, glibc-2.27-r6, 4.19.23-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.19.23-gentoo-x86_64-Intel-R-_Core-TM-_i5-7500_CPU_@_3.40GHz-with-gentoo-2.6
KiB Mem:     2026348 total,    901884 free
KiB Swap:    8126460 total,   8120820 free
Timestamp of repository gentoo: Fri, 01 Mar 2019 00:45:01 +0000
Head commit of repository gentoo: 8c23251599a57a3c53fffa11f6d102116dcb24af
sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.30 p5) 2.30.0
app-shells/bash:          4.4_p23-r1::gentoo
dev-lang/perl:            5.26.2::gentoo
dev-lang/python:          2.7.15::gentoo, 3.6.5::gentoo
dev-util/cmake:           3.9.6::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.30-r4::gentoo
sys-devel/gcc:            8.2.0-r6::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 4.14-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.27-r6::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts:
    sync-rsync-verify-max-age: 24

gentoo-custom
    location: /usr/local/portage
    masters: gentoo
    priority: 0

deepin
    location: /var/lib/layman/deepin
    masters: gentoo
    priority: 50

gentoo-zh
    location: /var/lib/layman/gentoo-zh
    masters: gentoo
    priority: 50

unity-gentoo
    location: /var/lib/layman/unity-gentoo
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirrors.163.com/gentoo/ http://mirrors.ustc.edu.cn/gentoo/"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j4"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl alsa amd64 berkdb bzip2 cli crypt cxx dri fortran gdbm iconv ipv6 libtirpc multilib ncurses nls nptl openmp pam pcre qt5 readline seccomp ssl systemd tcpd udev unicode xattr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="keyboard libinput mouse evdev vmmouse" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-1" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby24" USERLAND="GNU" VIDEO_CARDS="intel nouveau radeon radeonsi vmware" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LANG, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by zhtengw** [comment]
Yes, because of the network-sanbox FEATURE, some of the packages can not install. Now I have rewritten the ebuilds related. Please sync and try update.

**Comment by zhtengw** [comment]
Fixed with https://github.com/zhtengw/deepin-overlay/commit/998e8e3f4a5a4ad9b0b251575fa9c482eb9c3317
