### ISSUE TITLE
media-gfx/deepin-screen-recorder-2.7.7::deepin : Won't open on bedrock linux using gentoo strata, no errors.

### ISSUE THREAD

**Issue by Kreyren** [zhtengw/deepin-overlay#55]
`media-gfx/deepin-screen-recorder-2.7.7::deepin` : Won't open on bedrock linux using gentoo strata, no errors.

![image](https://user-images.githubusercontent.com/11302521/55978389-a4fe9980-5c87-11e9-82ce-472d75459d50.png)

Excluded bedrock issue since the issue is same using `strat -r gentoo deepin-screen-recorder` which is equvivalent of `chroot /mnt/gentoo deepin-screen-recorder` and method to exclude bedrock functions. 

![image](https://user-images.githubusercontent.com/11302521/55978549-ebec8f00-5c87-11e9-89aa-0d130bd62a45.png)

**Comment by zhtengw** [comment]
Oh, I see. You should enable at least one of the two USE flags (git or mp4). Without these, the deepin-screen-recorder won't start and recorde anything.

**Comment by Kreyren** [comment]
Fixed in https://github.com/Kreyren/deepin-overlay/commit/d7abafc34e4fd36feb90bb46d1740560c7715542 based on https://github.com/zhtengw/deepin-overlay/issues/55#issuecomment-486178061

**Comment by zhtengw** [comment]
Hi @Kreyren , thank you for your report. I have added a "REQUIRED_USE" in the ebuild to avoid this issue.
