### ISSUE TITLE
Can't find any docs

### ISSUE THREAD

**Issue by TheDevKiller** [zhtengw/deepin-overlay#56]
It looks very difficult to install Deepin on Gentoo, especially when using OpenRC and I can't find any docs. No wiki, or tutorial ... I'm completely lost. Could you add some docs, a little tutorial or can someone explain me how to install Deepin on Gentoo?

**Comment by zhtengw** [comment]
[dde-daemon](https://github.com/linuxdeepin/dde-daemon), which is the base runtime daemon of DDE, can not run without systemd. You can run "emerge -av dde-meta" to install Deepin Desktop Evironment. 
PS: I am the only maintainer of deepin-overlay, and I don't have enough time and energy to patch DDE
to run without systemd. I will be appreciative if someone can help me.

**Comment by TheDevKiller** [comment]
OK so I can't do that. Thanks, I think I'll try KDE or/and stay on i3 for now ^^

**Comment by zhtengw** [comment]
Hi @TheDevKiller , I spend some time this weekend to do a clean installation of gentoo and DDE. And I try to build up DDE without systemd.
If you are still interested in DDE, could you please refer the guide in README.md and have a try? Please let me know when meet any issues.

**Comment by TheDevKiller** [comment]
OK I'll check it this afternoon, thanks

**Comment by Fomys** [comment]
I'm currently follow the readme to install deepin on openrc but when I install dde-base/dde-meta I have the following error:
```sudo emerge -av dde-base/dde-meta

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "~dev-qt/qtgui-5.12.3".
(dependency required by "dev-qt/qtxcb-private-headers-5.12.3::deepin" [ebuild])
(dependency required by "dev-qt/qt5dxcb-plugin-1.1.27::deepin" [ebuild])
(dependency required by "dde-base/dde-qt5integration-0.3.11::deepin" [ebuild])
(dependency required by "dde-base/deepin-menu-3.4.4::deepin" [ebuild])
(dependency required by "dde-extra/deepin-terminal-3.2.2.1::deepin" [ebuild])
(dependency required by "dde-base/dde-meta-15.10::deepin[terminal]" [ebuild])
(dependency required by "dde-base/dde-meta" [argument])
```

**Comment by zhtengw** [comment]
@Fomys, you should sync your system’s portage tree first.

**Comment by zhtengw** [comment]
Wiki added, close this issue now.
