### ISSUE TITLE
dde-base/dde-qt-dbus-factory requires dev-qt/qtgui:5 as dependency

### ISSUE THREAD

**Issue by IAmMattD** [zhtengw/deepin-overlay#6]
When building dde-base/dde-qt-dbus-factory (build whole dde-meta from scratch), I encounter below error:

    Project ERROR: Unknown module(s) in QT: gui
    make[1]: *** [Makefile:43: sub-qdbusxml2cpp-make_first] Error 3
    make[1]: Leaving directory '/var/tmp/portage/dde-base/dde-qt-dbus-factory-0.0.3/work/dde-qt-dbus-factory-0.0.3/tools'
    make: *** [Makefile:44: sub-tools-make_first] Error 2
And after I install dev-qt/qtgui, this issue is solved.

So I suppose, dde-base/dde-qt-dbus-factory requires dev-qt/qtgui:5 as dependency.

Could you check it?

**Comment by zhtengw** [comment]
Confirmed. There are 
```
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
...
LIBS          = $(SUBLIBS) -lQt5Gui -lQt5DBus -lQt5Core -lGL -lpthread 
```
in tools/qdbusxml2cpp/Makefile.

But I cannot find any source code included QtGui and there is no qtgui dependency in debian/control. Maybe it is a issue related to how qmake generate Makefile. I will add qtgui in DEPEND to avoid this. Thank you.
