### ISSUE TITLE
deepin-wallpapers 

### ISSUE THREAD

**Issue by javashin** [zhtengw/deepin-overlay#61]
look for image-blur on  /usr/lib and im on gentoo 64

>>> Emerging (12 of 38) dde-base/deepin-wallpapers-1.7.7::deepin
 * deepin-wallpapers-1.7.7.tar.gz SHA256 size ;-) ...                                                               [ ok ]
 * FEATURES='assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr'
 * CFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu'
 * CXXFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu'
 * CPPFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe'
 * FFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu'
 * FCFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu'
 * F77FLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu'
 * LDFLAGS='-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe'
 * MAKEOPTS='-j3'
 * gcc (Gentoo 9.1.0-r1 p1.1) 9.1.0
 * Linux igloo-l440 5.1.15-jsX #1 SMP PREEMPT Tue Jun 25 16:12:33 AST 2019 x86_64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz GenuineIntel GNU/Linux
>>> Unpacking source...
>>> Unpacking deepin-wallpapers-1.7.7.tar.gz to /var/tmp/portage/dde-base/deepin-wallpapers-1.7.7/work
>>> Source unpacked in /var/tmp/portage/dde-base/deepin-wallpapers-1.7.7/work
>>> Preparing source in /var/tmp/portage/dde-base/deepin-wallpapers-1.7.7/work/deepin-wallpapers-1.7.7 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dde-base/deepin-wallpapers-1.7.7/work/deepin-wallpapers-1.7.7 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dde-base/deepin-wallpapers-1.7.7/work/deepin-wallpapers-1.7.7 ...
make -j3 
/usr/lib/deepin-api/image-blur --sigma 30 deepin/Flowing_Ribbon.jpg image-blur/b0987cf0c936a18e0f020366cddb63ee.jpg
make: /usr/lib/deepin-api/image-blur: Command not found
make: *** [Makefile:13: blur/deepin/Flowing_Ribbon.jpg] Error 127

i made a symlink  of /usr/lib64/deepin-api/image-blur  to /usr/lib/deepin-api/image-blur
and emerges fine

**Comment by zhtengw** [comment]
Thank you, I will fix it.

**Comment by zhtengw** [comment]
Fixed with https://github.com/zhtengw/deepin-overlay/commit/6afc6fe6ed826daaa5238e20924bb97c3f64a258
