### ISSUE TITLE
  Error in installing deepin-terminal and how to solve it

### ISSUE THREAD

**Issue by leenas2019** [zhtengw/deepin-overlay#64]
/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0/./main.vala:258.17-258.42: warning: Gtk.Window.set_has_resize_grip has been deprecated since 3.14
xcb.vapi:373.3-373.40: error: missing return statement at end of subroutine body
                public VoidCookie image_text_8_checked (Drawable drawable, GContext gc, int16 x, int16 y, string text) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:379.3-379.32: error: missing return statement at end of subroutine body
                public VoidCookie image_text_8 (Drawable drawable, GContext gc, int16 x, int16 y, string text) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:411.3-411.48: error: missing return statement at end of subroutine body
                public AllocNamedColorCookie alloc_named_color (Colormap cmap, string name) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:417.3-417.58: error: missing return statement at end of subroutine body
                public AllocNamedColorCookie alloc_named_color_unchecked (Colormap cmap, string name) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:439.3-439.45: error: missing return statement at end of subroutine body
                public VoidCookie store_named_color_checked (ColorFlag flags, Colormap cmap, uint32 pixel, string name) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:445.3-445.37: error: missing return statement at end of subroutine body
                public VoidCookie store_named_color (ColorFlag flags, Colormap cmap, uint32 pixel, string name) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:456.3-456.39: error: missing return statement at end of subroutine body
                public LookupColorCookie lookup_color (Colormap cmap, string name) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xcb.vapi:462.3-462.49: error: missing return statement at end of subroutine body
                public LookupColorCookie lookup_color_unchecked (Colormap cmap, string name) {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0/widget/window.vala:530.22-530.35: warning: local variable `is_light_theme' declared but never used
                bool is_light_theme = is_light_theme();
                     ^^^^^^^^^^^^^^
Compilation failed: 8 error(s), 72 warning(s)
make[2]: *** [CMakeFiles/deepin-terminal.dir/build.make:123: main.c] Error 1
make[2]: Leaving directory '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0_build'
make[1]: *** [CMakeFiles/Makefile2:775: CMakeFiles/deepin-terminal.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0_build'
make: *** [Makefile:130: all] Error 2
 * ERROR: dde-extra/deepin-terminal-5.0.0::deepin failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dde-extra/deepin-terminal-5.0.0::deepin'`,
 * the complete build log and the output of `emerge -pqv '=dde-extra/deepin-terminal-5.0.0::deepin'`.
 * The complete build log is located at '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0_build'
 * S: '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0'
>>> Failed to emerge dde-extra/deepin-terminal-5.0.0, Log file:

>>>  '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/temp/build.log'
*** Resuming merge...

These are the packages that would be merged, in order:

Calculating dependencies... done!

Total: 0 packages, Size of downloads: 0 KiB
 * emerge --keep-going: dde-base/dde-meta-15.10.1 dropped because it requires
 * dde-extra/deepin-terminal

 * Messages for package dde-extra/deepin-terminal-5.0.0:

 * ERROR: dde-extra/deepin-terminal-5.0.0::deepin failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dde-extra/deepin-terminal-5.0.0::deepin'`,
 * the complete build log and the output of `emerge -pqv '=dde-extra/deepin-terminal-5.0.0::deepin'`.
 * The complete build log is located at '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0_build'
 * S: '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/work/deepin-terminal-5.0.0'

 * Messages for package dde-base/dde-meta-15.10.1:

 * emerge --keep-going: dde-base/dde-meta-15.10.1 dropped because it requires
 * dde-extra/deepin-terminal
 * 
 * The following 2 packages have failed to build, install, or execute
 * postinst:
 * 
 *  (dde-extra/deepin-terminal-5.0.0:0/0::deepin, ebuild scheduled for merge), Log file:
 *   '/var/tmp/portage/dde-extra/deepin-terminal-5.0.0/temp/build.log'
 *  (dde-base/dde-meta-15.10.1:0/0::deepin, ebuild scheduled for merge)

**Comment by zhtengw** [comment]
Downgrading dev-lang/vala to 0.44.7, then deepin-terminal can be built.

**Comment by leenas2019** [comment]
> Downgrading dev-lang/vala to 0.44.7, then deepin-terminal can be built.

Ok, thank you.
