### ISSUE TITLE
Error in emerge dde-meta, net-dialup/lrzsz cannot be installed

### ISSUE THREAD

**Issue by leenas2019** [zhtengw/deepin-overlay#65]
......
Applying Irzsz-implicit-decl.patch....
Applying Irzsz-0.12.20-automake-1.12.patch ...
* Applying Irzsz-0.12.20-automake-1.13.patch ..
* Running eautoreconf in '/uar/tmp/portage/net-dialup/lrzsz-0.12.20-r4/work/lrzsz-0.12.201 * Running aclocal
* This package has a configure.in file which has long been deprecated. Please 
* update it to use configure.ac instead as newer versions of autotools will die 
* when it finds this file. See https://bugs.gentoo.org/426262 for details * Running autoconf --force ...
* Failed Running autoconf!
* Include in your bugreport the contents, of
*     /var/tmp/portage/net-dialup/lrzsz-0.12.20-r4/temp/autoconf.out
* ERROR: net-dialup/lrzsz-0.12.20-r4: :gentoo failed (prepare phase): 
*      Failed Running autoconf
* Call stack:
*         ebuild.sh, line 125: Called src_prepare
*     environment, line 1866: Called eautoreconf
*     environment, line 970: Called eautoconf '--force"
*     enuironment, line 883: Called autotools_run_tool '--at-m4flags' 'autoconf' '--force' 
*     environment, line 697: Called die
* The specific snippet of code:
                  die "Failed Running $1 !"
* If you need support, post the output of 'emerge --info '=net-dialup/lrzsz-0.12.20-r4::gentoo'`,
*  the complete build log and the output of `emerge -pqu '=net-dialup/lrzsz-0.12.20-r4::gentoo'`.
* The complete build log is located at '/var/tmp/portage/net-dialup/lrzsz-0.12.20-r4/temp/build. log'.
* The ebuild enuironment file is located at '/var/tmp/portage/met-dialup/lrzsz-0.12.20-r4/temp/environment'.
........

autoconf.out
***** autoconf ******
***** PMD : /var/tmp/portage/net-dialup/lrzsz-0.12.20-r4/work/lrzsz-0.12.20
***** autoconf --force
ERROR: Use of AM_GNU_GETTEXT without [external] argunent is no longer support.
configure.in:99: warning: AM_INTL_SUBDIR is m4_require'd but not m4_defun' d
aclocal.m4:77: AM_GNU_GETEXT is expanded from...
configure.in:99: the top level
configure:5105: error: possibly undefined macro: AM_INTL_SUBDIR 
    If this token and others are legitimate, please use m4_pattern_allow.
    See, the Autoconf documentation.

**Comment by zhtengw** [comment]
Please follow this issue in Gentoo's bugzilla https://bugs.gentoo.org/685696.
