### ISSUE TITLE
dde-base/dde-control-center requires dev-qt/qtsql:5 as dependency

### ISSUE THREAD

**Issue by IAmMattD** [zhtengw/deepin-overlay#7]
I suppose this issue is similar with my previous reported issue for dde-base/dde-qt-dbus-factory.

Following error occurs during the build:

    Project ERROR: Unknown module(s) in QT: sql
    make: *** [Makefile:69: sub-frame-make_first] Error 3
    make: *** Waiting for unfinished jobs....

To help further investigate the issue, I will append build log in future issues.
[buildlog.txt](https://github.com/zhtengw/deepin-overlay/files/721964/buildlog.txt)

**Comment by zhtengw** [comment]
Yes. Ebuilds edited
