### ISSUE TITLE
problem emerging dev-go/go-dbus-generator-0.6.6-r1 in gentoo amd 64

### ISSUE THREAD

**Issue by funky-gibbon** [zhtengw/deepin-overlay#72]
Dear All,

I tried to emerge dev-go/go-dbus-generator-0.6.6-r1 on an amd64 kaveri box running gentoo stable as part of an install of deepin desktop.

See here:

https://bugs.gentoo.org/718776
and
https://forums.gentoo.org/viewtopic-t-1111810.html)

```
* Messages for package dev-go/go-dbus-generator-0.6.6-r1:

 * Package:    dev-go/go-dbus-generator-0.6.6-r1
 * Repository: deepin
 * Maintainer: atenzd@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * ERROR: dev-go/go-dbus-generator-0.6.6-r1::deepin failed (prepare phase):
 *   eapply_user (or default) must be called in src_prepare()!
 *
 * Call stack:
 *            ebuild.sh, line  762:  Called __ebuild_main 'prepare'
 *   phase-functions.sh, line 1054:  Called __dyn_prepare
 *   phase-functions.sh, line  395:  Called die
 * The specific snippet of code:
 *         die "eapply_user (or default) must be called in src_prepare(
```)!"

Suggestions welcome.

Regards

Michael Fothergill

**Comment by zhtengw** [comment]
Fixed with commit a180df6.

**Comment by funky-gibbon** [comment]
A great many thanks to you for fixing the bug here.  I ran emerge --sync deepin and the 2 packages plus an extra 22 installed correctly.

I am now running deepin version 15.11

God bless all the brave people of Wuhan.

Regards

MF

**Comment by funky-gibbon** [comment]
A great many thanks for this.

Version 15.11 of deepin is running correctly now.

Regards

MF
