### ISSUE TITLE
dev-qt/qcef-1.1.7-r1::deepin	fails to emerge in gentoo amd64 stable

### ISSUE THREAD

**Issue by funky-gibbon** [zhtengw/deepin-overlay#73]
Dear All,

Package dev-qt/qcef-1.1.7-r1::deepin	fails to emerge in gentoo amd64 stable (running on a kaveri pc).

See here:

https://forums.gentoo.org/viewtopic-t-1111812.html
 and the build.log file:
http://dpaste.com/2J6QXK6

The suggested solution is:

In qt-5.14 QFileDialog::setConfirmOverwrite(bool) is deprecated and developer should change with QFileDialog::setOption(QFileDialog::Option option, bool on = true).

Cheers

Michael Fothergill

**Comment by zhtengw** [comment]
This was fixed in v20 branch, I merge this into master now.
