### ISSUE TITLE
Problem emerging dev-go/go-dbus-factory-1.6.4

### ISSUE THREAD

**Issue by kumarayush2104** [zhtengw/deepin-overlay#75]
[build.log](https://github.com/zhtengw/deepin-overlay/files/4570219/build.log)

**Comment by zhtengw** [comment]
Commit f7a4588 may fix this.

**Comment by kumarayush2104** [comment]
Got a new error


Gio-2/go :- undefined glib.Source

**Comment by zhtengw** [comment]
> Got a new error
> 
> Gio-2/go :- undefined glib.Source

Which package complained this? Could you please show the full log?

**Comment by zhtengw** [comment]
I found out that it is a bug for go-gir-generator with dev-libs/glib-2.64. It should be fix with commit 4e0dccb.

**Comment by kumarayush2104** [comment]
Thanks, it solved the issue, but i got a error in x11-libs/bamf ![](https://i.imgur.com/IocvLHc.jpg)

**Comment by zhtengw** [comment]
@kumarayush2104 Fixed with commit 6d22f02.

**Comment by zhtengw** [comment]
Since the issue of dev-go/go-dbus-factory-1.6.4 was resolved. I close this issue. 
Feel free to open issues if you meet any other problems.
