### ISSUE TITLE
Size of dev-qt/qt5dxcb-plugin-5.0.11 

### ISSUE THREAD

**Issue by kumarayush2104** [zhtengw/deepin-overlay#76]
I guess size of dev-qt/qt5dxcb-plugin-5.0.11 is updated 

![](https://i.imgur.com/YpkNpF5.jpg)

**Comment by zhtengw** [comment]
Thank you. Updated

**Comment by zhtengw** [comment]
The repo was renamed by upstream. I have created new ebuilds.

**Comment by kumarayush2104** [comment]
Thanks, finally deepin compiled and working fine,

How can i change the wm from kwin to deepin-wm ??

Windows effects are not toggling

**Comment by zhtengw** [comment]
> Thanks, finally deepin compiled and working fine,
> 
> How can i change the wm from kwin to deepin-wm ??
> 
> Windows effects are not toggling


USE=“mutter -kwin” emerge -v dde-meta
Then
emerge -aC dde-kwin

**Comment by kumarayush2104** [comment]
Windows effects are not working.... Only works when using root account..

**Comment by zhtengw** [comment]
@kumarayush2104 Window Effect can also be toggled with dde-kwin, see linuxdeepin/developer-center#2610

**Comment by kumarayush2104** [comment]
Thank you very much
