### ISSUE TITLE
xcur2png distfile unavailable

### ISSUE THREAD

**Issue by threeway** [zhtengw/deepin-overlay#8]
Attempting to install dde-meta and xcur2png seems to try to pull from cli-apps.org which seems to be blocked behind some sort of login?

This may be a temporary issue, but is there another place to find the distfile?

**Comment by zhtengw** [comment]
Confirmed.
I tried to visit http://cli-apps.org and got that info "This site is no longer available."

I will find the new download page for xcur2png. Before that, you can use the tarball I uploaded.

Just download this tarball file and move it into /usr/portage/distfiles/
[xcur2png-0.7.1.tar.gz](https://github.com/zhtengw/deepin-overlay/files/823155/xcur2png-0.7.1.tar.gz)

**Comment by zhtengw** [comment]
Hi, @threeway. Since the home page of xcur2png is lost and I can not find the new home page of it. I just use the download address of xcur2png-0.7.1.tar.gz in this page as SRC_URI.

**Comment by threeway** [comment]
Can confirm that this fixes the issue, thanks for the fast response!
