### ISSUE TITLE
dde-base/dde-daemon-5.11.0.1 can't be download 

### ISSUE THREAD

**Issue by kumarayush2104** [zhtengw/deepin-overlay#89]
dde-base/dde-daemon's git repo can't be found, please look into it 😊

**Comment by kumarayush2104** [comment]
I edited the repo from 5.11.0.1 to 5.10.0.1 and its checksums, it compiled successfully..

**Comment by zhtengw** [comment]
The 5.11.0.1 tag was removed in the dde-daemon repo. Bump 5.11.0.0 version now. https://github.com/zhtengw/deepin-overlay/commit/29881936f3e8119b04dc4a7e9cd7181b3f379842
