### ISSUE TITLE
dde 安装xcur2png总是报错

### ISSUE THREAD

**Issue by luojing8431** [zhtengw/deepin-overlay#94]
[xcur2png-build.log](https://github.com/zhtengw/deepin-overlay/files/4804884/xcur2png-build.log)

**Comment by zhtengw** [comment]
这个是网络问题，你可以直接下载 https://github.com/eworm-de/xcur2png/releases/download/0.7.1/xcur2png-0.7.1.tar.gz ，把这个源码包放到/usr/portage/distfiles/目录，然后重试。

**Comment by luojing8431** [comment]
多谢大神，第一次发帖在git还不懂规矩，抱歉，我试一下，然后改帖子


 
---原始邮件---
发件人: "Aten Zhang"<notifications@github.com&gt;
发送时间: 2020年6月19日 21:22:42
收件人: "zhtengw/deepin-overlay"<deepin-overlay@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"luojing8431"<25161811@qq.com&gt;;
主题: Re: [zhtengw/deepin-overlay] dde 安装xcur2png总是报错 (#94)




 
这个是网络问题，你可以直接下载 https://github.com/eworm-de/xcur2png/releases/download/0.7.1/xcur2png-0.7.1.tar.gz ，把这个源码包放到/usr/portage/distfiles/目录，然后重试。

**Comment by luojing8431** [comment]
还有27个包不行，都放在/usr/portage/distfiles/目录里运行emerge吗？

**Comment by zhtengw** [comment]
哦，没有/usr/portage/distfiles/的话，那你的gentoo应该是最近才安装的，源码目录应该是/var/cache/distfiles，放到/var/cache/distfiles里去
