### ISSUE TITLE
dde 安装xcur2png总是报错，系统的另一个错误

### ISSUE THREAD

**Issue by luojing8431** [zhtengw/deepin-overlay#95]
[cups-filters-build.log](https://github.com/zhtengw/deepin-overlay/files/4804878/cups-filters-build.log)

**Comment by zhtengw** [comment]
这个是安装cups-filters-1.27.4的错误提示，这里没法处理，可以bugs.gentoo.org搜索看看有没有解决方案。一个可能[相关的bug](https://bugs.gentoo.org/719052)。

PS：发log信息的话，最好是上传文件，直接大段贴上来很难看清楚。如果错误提示很短而且信息明确，可以用\`\`\`括起来。
