### ISSUE TITLE
继续卡住，哈哈

### ISSUE THREAD

**Issue by luojing8431** [zhtengw/deepin-overlay#97]
emerge --ask dde-meta

These are the packages that would be merged, in order:

Calculating dependencies -

!!! Problem resolving dependencies for dde-base/dde-meta
... done!

!!! The ebuild selected to satisfy "dde-meta" has unmet requirements.
- dde-base/dde-meta-20::deepin USE="kwin mutter systemd terminal (-elogind) -extra -grub -manual -multimedia -plymouth -policykit -screensaver -turbo" ABI_X86="(64)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    at-most-one-of ( kwin mutter )

  The above constraints are a subset of the following complete expression:
    exactly-one-of ( systemd elogind ) at-most-one-of ( kwin mutter )

**Comment by zhtengw** [comment]
提示已经很清楚了
```
The following REQUIRED_USE flag constraints are unsatisfied:
at-most-one-of ( kwin mutter )
```
`kwin` 和`mutter`这两个USE flag最多选一个，要不`USE="kwin -mutter"`，要么`USE="mutter -kwin"`
