### ISSUE TITLE
dde-kwin build error

### ISSUE THREAD

**Issue by luojing8431** [zhtengw/deepin-overlay#98]
kwin过不去，考验耐心
[dde-kwin-5.1.0.3-biuld.log](https://github.com/zhtengw/deepin-overlay/files/4808610/dde-kwin-5.1.0.3-biuld.log)

emerge --ask dde-meta

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] x11-wm/dde-kwin-5.1.0.3 
[ebuild  N     ] dde-extra/deepin-terminal-5.0.4.1  USE="zssh" 
[ebuild  N     ] virtual/dde-wm-0  USE="kwin minimal -mutter" 
[ebuild  N     ] dde-base/dde-daemon-5.11.0.0  USE="systemd -bluetooth (-elogind) -grub" 
[ebuild  N     ] dde-base/startdde-5.5.0.1 
[ebuild  N     ] dde-base/dde-dock-5.1.0.11-r1 
[ebuild  N     ] dde-base/dde-launcher-5.2.0.3 
[ebuild  N     ] dde-base/dde-clipboard-5.0.0.3 
[ebuild  N     ] dde-base/dde-control-center-5.2.0.3  USE="systemd -redshift" 
[ebuild  N     ] dde-base/dde-file-manager-5.1.1.25-r1  USE="-avfs -samba -screensaver" 
[ebuild  N     ] dde-base/dde-session-shell-5.1.0.1  USE="systemd (-elogind)" 
[ebuild  N     ] dde-base/dde-session-ui-5.2.0.3  USE="systemd (-elogind)" 
[ebuild  N     ] dde-base/dde-meta-20  USE="kwin systemd terminal (-elogind) -extra -grub -manual -multimedia -mutter -plymouth -policykit -screensaver -turbo" 

Would you like to merge these packages? [Yes/No]

**Comment by zhtengw** [comment]
1. 首先回答你标题的问题：`dde-wm只能设置Use kwin -mutter ，不能-kwin mutter`。这个原因可能是你的`make.conf`和`package.use`里的关于USE flag的设置有冲突，请自己检查。

2. 关于dde-kwin编译出错的问题，我这里没有重现，请问你的kde-plasma/kwin是什么版本？

**Comment by zhtengw** [comment]
发现原因了，貌似kde 5.19把kwayland中的server部分又独立出来了，我看看怎么加个补丁，可能要稍等一段时间。

**Comment by zhtengw** [comment]
我系统里的kwin还是5.18版本，没那么快能测试，你更新一下仓库，看看dde-kwin-5.1.0.3-r1有没有解决你的问题

**Comment by luojing8431** [comment]
我这刷新只有x11-wm/dde-kwin-5.1.0.3

**Comment by zhtengw** [comment]
> 
> 
> 我这刷新只有x11-wm/dde-kwin-5.1.0.3

有的，请刷新deepin-overlay仓库

**Comment by luojing8431** [comment]
试了，dde-kwin-5.1.0.3-r1 过不去，耐心等着

**Comment by luojing8431** [comment]
顺便问一句，安装dde后，dde的软件都能用吗？

**Comment by zhtengw** [comment]
> 
> 
> 顺便问一句，安装dde后，dde的软件都能用吗？

只要是deepin团队的开源软件，都可以安装使用，具体可以看dde-base 和dde-extra分类下的列表

**Comment by zhtengw** [comment]
> 
> 
> 顺便问一句，安装dde后，dde的软件都能用吗？比如deepinwine？

deepin-wine现阶段没办法，参见https://github.com/microcai/gentoo-zh/issues/553#issuecomment-567314543

**Comment by zhtengw** [comment]
> 
> 
> 试了，dde-kwin-5.1.0.3-r1 过不去，耐心等着

是补丁文件有个打字错误，现已修复，可以了。

**Comment by luojing8431** [comment]
dde-kwin-5.1.0.3-r1 ，到最后一点点还是报了个错，更新一下，然后再试，貌似剩12个包了

**Comment by zhtengw** [comment]
我已经升级了kwin到5.19，dde-kwin编译是通过了的。如果你那边仍然有错，而且错误不同于之前，也麻烦附上build.log.

**Comment by luojing8431** [comment]
[dde-kwin-build.log](https://github.com/zhtengw/deepin-overlay/files/4809727/dde-kwin-build.log)
错误太复杂，我看不懂了

**Comment by luojing8431** [comment]
过去了，unmerge 了一个plasma的什么包，继续安装了，多谢大神，离目标又近(ง •̀_•́)

**Comment by zhtengw** [comment]
> 
> 
> [dde-kwin-build.log](https://github.com/zhtengw/deepin-overlay/files/4809727/dde-kwin-build.log)
> 错误太复杂，我看不懂了

噢，跟kdeplasma-addons有文件冲突，在dde-kwin官方仓库找到了补丁，已修复。

**Comment by luojing8431** [comment]
我是把kdeplasma-addons给卸了，还有6个包正在装，嘻嘻，能用slim管理登陆不？我也喜欢xfce4

**Comment by zhtengw** [comment]
> 
> 
> 我是把kdeplasma-addons给卸了，还有6个包正在装，嘻嘻，能用slim管理登陆不？我也喜欢xfce4

其他显示管理器要自行配置，一般来说只要能显示出来Deepin的Session，应该是没问题的。

**Comment by luojing8431** [comment]
dde-base/dde-control-center-5.2.0.4这个包下不下来....哪里能下，到本地装

**Comment by zhtengw** [comment]
> 
> 
> dde-base/dde-control-center-5.2.0.4这个包下不下来....哪里能下，到本地装

都是从deepin的官方github仓库的release页面下载的，具体GitHub地址可以通过`eix ”包名“`看到。
https://github.com/linuxdeepin/dde-control-center/archive/5.2.0.4.tar.gz

**Comment by luojing8431** [comment]
安装都没问题，启动起来，黑屏然后一个鼠标，就啥进度也没有了，这是啥情况？

**Comment by luojing8431** [comment]
感谢zhtengw 大神，循循善诱，不厌其烦，感谢！学了不少知识，点赞

**Comment by zhtengw** [comment]
> 
> 
> 安装都没问题，启动起来，黑屏然后一个鼠标，就啥进度也没有了，这是啥情况？运行过程中我装的virtualbox的kernel没有启动啥的，然后就没有啥进度了

黑屏只有鼠标应该是因为dde-kwin读取`$HOME/.config/kwinrc`出错，一般注销桌面重新进入就好了。

**Comment by zhtengw** [comment]
> 
> 
> 感谢zhtengw 大神，循循善诱，不厌其烦，感谢！学了不少知识，点赞！！已经快乐的在gentoo-dde下面啦，办公室是deepin20,很好用，deepin，加油！

不客气，个人其实没用过deepin，只是喜欢deepin团队的开源软件和他们的精神。欢迎多多帮忙测试。
