### ISSUE TITLE
blank desktop (startx /use/bin/startdde)

### ISSUE THREAD

**Issue by kumarayush2104** [zhtengw/deepin-overlay#99]
[  151.170169] traps: dde-dock[3280] trap int3 ip:7fe11a835175 sp:7ffe047574f0 error:0 in libglib-2.0.so.0.6200.6[7fe11a7fb000+81000]
[  151.182060] traps: dde-dock[3282] trap int3 ip:7f16b0849175 sp:7ffe963dd040 error:0 in libglib-2.0.so.0.6200.6[7f16b080f000+81000]
[  154.394203] traps: dde-desktop[3296] trap int3 ip:7f24115a0175 sp:7fff611b0090 error:0 in libglib-2.0.so.0.6200.6[7f2411566000+81000]
[  165.974293] traps: dde-dock[3517] trap int3 ip:7fd381c79175 sp:7ffd337dbad0 error:0 in libglib-2.0.so.0.6200.6[7fd381c3f000+81000]
[  166.026995] traps: dde-desktop[3523] trap int3 ip:7f7330811175 sp:7ffd76d140e0 error:0 in libglib-2.0.so.0.6200.6[7f73307d7000+81000]
[  176.087000] traps: dde-dock[3595] trap int3 ip:7fed03e9a175 sp:7fff227ca640 error:0 in libglib-2.0.so.0.6200.6[7fed03e60000+81000]
[  176.142810] traps: dde-desktop[3601] trap int3 ip:7ff65e94f175 sp:7ffe577ad220 error:0 in libglib-2.0.so.0.6200.6[7ff65e915000+81000]
[  177.067637] traps: dde-file-manage[3632] trap int3 ip:7ff412db8175 sp:7ffd31e89d60 error:0 in libglib-2.0.so.0.6200.6[7ff412d7e000+81000]
[  186.205512] traps: dde-dock[3686] trap int3 ip:7f71a548a175 sp:7fff0dcce430 error:0 in libglib-2.0.so.0.6200.6[7f71a5450000+81000]
[  186.259376] traps: dde-desktop[3692] trap int3 ip:7fa3f0e10175 sp:7ffc539f28c0 error:0 in libglib-2.0.so.0.6200.6[7fa3f0dd6000+81000]
[  190.575612] traps: dde-control-cen[3652] trap int3 ip:7f65c1531175 sp:7fffa1e61700 error:0 in libglib-2.0.so.0.6200.6[7f65c14f7000+81000]
[  196.319403] traps: dde-dock[3749] trap int3 ip:7fdb4395c175 sp:7ffdab9591a0 error:0 in libglib-2.0.so.0.6200.6[7fdb43922000+81000]
[  196.371253] traps: dde-desktop[3755] trap int3 ip:7fdafd514175 sp:7ffc7a03c2c0 error:0 in libglib-2.0.so.0.6200.6[7fdafd4da000+81000]
[  206.426751] traps: dde-dock[3788] trap int3 ip:7f213e957175 sp:7ffcd2e72c90 error:0 in libglib-2.0.so.0.6200.6[7f213e91d000+81000]
[  206.478956] traps: dde-desktop[3794] trap int3 ip:7f8f67a99175 sp:7ffee418f050 error:0 in libglib-2.0.so.0.6200.6[7f8f67a5f000+81000]

**Comment by luojing8431** [comment]
感谢大神，我弄好了，在slim里加了一个deepin的启动，非常满意，谢谢！

**Comment by zhtengw** [comment]
Remerge dde-dock and dde-file-manager may fix this.
